version: "3.7"


services:

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: ip_db
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8085:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@test.com
      PGADMIN_DEFAULT_PASSWORD: root

  php:
    build: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
    user: 1000:1000

  nginx:
    image: nginx:1.17
    ports:
      - 8081:80
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

  node:
    build: ./docker/node
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8082:8081
    #user: 1000:1000
